USE ktdb_stock;
INSERT INTO `items` VALUES
('', 'Paint Scraper 40mm','','0'),
('', 'GI Tee 0.5in Thai','','0'),
('', 'GI Nipple 0.5in Thai','','0'),
('', 'GI Socket 0.5in Thai','','0'),
('', 'GI Elbow 0.5in Thai','','0'),
('', 'Super Grif Bibcock 0.5in CP Long','','0'),
('', 'CP Reducer Nipple 0.75x0.5in','','0'),
('', 'CP Reducer Bush 0.5x0.375in','','0'),
('', 'Sanwa Bibcock 0.5in China','','0'),
('', 'So-Pure Water Filter Double','','0'),
('', 'Royal Wash Basin Mixer Single-Nob','','0'),
('', 'Super General Fan 12in Rechargeable','','0'),
('', 'PM Sink Mixer Single Hole Single Lever A01','','0'),
('', 'PM Wash Basin Mixer Single Lever','','0'),
('', 'PM Wash Basin Mixer Single Lever E1','','0'),
('', 'Hesanit Sink Mixer ','','0'),
('', 'Boosni Sink Mixer Single Hole ','','0'),
('', 'Hesanit Shower Mixer Single Lever ','','0'),
('', 'Delta Shower Mixer Lever','','0'),
('', 'Jomix Wash Basin Mixer Lever Tap','','0'),
('', 'Winbnix Sink Tap Wall','','0'),
('', 'Unique Sink Mixer New','','0'),
('', 'Keller Wash Basin Mixer Single Lever','','0'),
('', 'Jafa Wash Basin Mixer','','0'),
('', 'Belano Wash Basin Mixer Double Handle','','0'),
('', 'Belano Sink Mixer Single Lever','','0'),
('', 'Belano Shower Mixer Single Lever','','0'),
('', 'Belano Shower Mixer Double Handle','','0'),
('', 'Royal Shower Mixer Single Lever','','0'),
('', 'Unique Sink Mixer Single Lever ','','0'),
('', 'Aristone Mixer Single Hole CP','','0'),
('', 'Keller Shower Mixer Single Lever','','0'),
('', 'Drill Chuck 13mm (1/2)','','0'),
('', 'Drill Bit Set Germany ','','0'),
('', 'Tile Cutter','','0'),
('', 'LWD Wire Clip Round 12.0','','0'),
('', 'Cable Number 2.5mm (1)','','0'),
('', 'Cable Number 4mm (5)','','0'),
('', 'Cable Number 4mm (4)','','0'),
('', 'Stanly Tools Sheffield 18mm','','0'),
('', 'Rect Angle 12in','','0'),
('', 'Rect Angle 24in','','0'),
('', 'Felding knife lock-back','','0'),
('', 'Davey Pump Seal Kit -Impler','','0'),
('', 'Stanly Wheel Replacement ','','0'),
('', 'Drain Spring 15in 4.6m','','0'),
('', 'Aluminiaum Handle Door','','0'),
('', 'Relexaflex Shower Pipe 150cm','','0'),
('', 'Rubicon Screw Driver Set ','','0'),
('', 'Measure Tape 50m','','0'),
('', 'Lupus Cutting Blade 4.5in Large','','0'),
('', 'Tianle Drill Locking  Shuk','','0'),
('', 'Valve Wire Stripper','','0'),
('', 'Self-Locing Hasp  Lock 4in','','0'),
('', 'Jixa Blade','','0'),
('', 'Flot Bits Wood 6ps','','0'),
('', 'Door Lock China ','','0'),
('', 'Laminate Cutter','','0'),
('', 'Royal Aviation cutter','','0'),
('', 'Cable Tie 150x3.6','','0'),
('', 'Cable Tie 150x2.5','','0'),
('', 'Cilecone Gun ','','0'),
('', 'Spray Gun','','0'),
('', 'Oxford Dmt Paint Brush 3x5/8','','0'),
('', 'Zilco Extention Wire 4g/3m','','0'),
('', 'Klastar Extention Wire 4g/3m','','0'),
('', 'Novex Extention Socket 4g/3m','','0'),
('', 'Qira Extention Socket 4g/3m','','0'),
('', 'Cable Tie  Small','','0'),
('', 'File Set 8in 5','','0'),
('', 'Tile Spacers ','','0'),
('', 'C-Clamp','','0'),
('', 'Lame Acieer Souple 20cm','','0'),
('', 'Pipe Cutter 1/8 – 1 1/4','','0'),
('', 'Wranch Double Open End  16x17','','0'),
('', 'Screw Driver 7pcs Set Kpicus','','0'),
('', 'Scraper Japan','','0'),
('', 'Cable Tie 450x76','','0'),
('', 'Gromix-Showers China','','0'),
('', 'Regen Bogen Shower Set Suding ','','0'),
('', 'Jasko Flush Tank ','','0'),
('', 'Ktte Flush Tank Malaysia','','0'),
('', 'Spirex Exhaust Fan 6in  NR-20','','0'),
('', 'Berkefeld Water Filter ','','0'),
('', 'Cable Joint ','','0'),
('', 'Heeco Pressure Control V','','0'),
('', 'C.R.I Pressure Control V','','0'),
('', 'Como Pressure Control V','','0'),
('', 'Grundfos Kit H Italy','','0'),
('', 'Aspa Pressure Control V','','0'),
('', 'C.R.I Pressure Control H','','0'),
('', 'Heeco Pressure Control H','','0'),
('', 'C.R.I Control Box 2hp','','0'),
('', 'C.R.I Control Box 1hp','','0'),
('', 'Control Box 2hp China','','0'),
('', 'Control Box 1hp China','','0'),
('', 'Extra Control Box 1hp','','0'),
('', 'Tarbo Pressure Kit H','','0'),
('', 'Awie Pressure Kit H','','0'),
('', 'Buraq Pressure Kit V','','0'),
('', 'Logicpress Pressure Kit ','','0'),
('', 'Heeco Flot Switch','','0'),
('', 'Unique Shattaf','','0'),
('', 'PM Shower Head ','','0'),
('', 'Omega Shower Head ','','0'),
('', 'Boosani Shattaf ','','0'),
('', 'PM Shower Head Round','','0'),
('', 'EMC Shattaf','','0'),
('', 'Jomix Shower Head ','','0'),
('', 'Milano Shattaf ','','0'),
('', 'Royal Shattaf','','0'),
('', 'Grohe Shattaf ','','0'),
('', 'Kala Shattaf','','0'),
('', 'Jomix Shattaf','','0'),
('', 'Oasi Shattaf','','0'),
('', 'Unique Shower Head Only 3 Function','','0'),
('', 'Heeco Shower Head ','','0'),
('', 'Roma Shattaf ','','0'),
('', 'Sicher Shower Set ','','0'),
('', 'Miro Shattaf  Italy','','0'),
('', 'HM Shattaf','','0'),
('', 'Jafa Shower  Mixer Set','','0'),
('', 'Jafa Wash Basin Mixer','','0'),
('', 'RB Shower Mixer','','0'),
('', 'RB Wash Basin Mixer','','0'),
('', 'Extension Reel 25m','','0'),
('', 'Royal Sink Mixer ','','0'),
('', 'Royal Kitchen Mixer Single Hole','','0'),
('', 'Royal Sink Mixer Lever Tap','','0'),
('', 'Admiral Wash Basin Mixer Two Hole','','0'),
('', 'Cartoon Sink Mixer 0.5in Wall','','0'),
('', 'Cartoon Basin Mixer Two Hole','','0'),
('', 'Cartoon Basin Mixer Single Hole','','0'),
('', 'Jomix Sink Mixer Single Hole Single Lever','','0'),
('', 'Speedy Fisher 6mm','','0'),
('', 'PM Sink Tap 0.5in','','0'),
('', 'Jasmin Sink Mixer Double Handle ','','0'),
('', 'XXX','','0'),
('', 'Doulton Water Filter MK11','','0'),
('', 'Bonus Sink Mixer Lever Tap','','0'),
('', 'Sicher Shower Set','','0'),
('', 'Sanwa Bibcock 0.75in','','0'),
('', 'Aramix Wash Basin Mixer Two Way Hole','','0'),
('', 'Kistenmacher Wash Basin Mixer Two Hole ','','0'),
('', 'XXX','','0'),
('', 'Kistenmacher Lavatory Mixer Bridge Type','','0'),
('', 'Kistenmacher Pillar Tap 0.5in','','0'),
('', 'Kistenmacher Built-in Valve 0.5in','','0'),
('', 'Kistenmacher Built-in Valve 0.75in','','0'),
('', 'Jomix CP Concealed Valve 0.75in','','0'),
('', 'Kistenmacher Shower Mixer Wall','','0'),
('', 'Admiral Basin Mixer Single Hole','','0'),
('', 'Perfect Fischer 8mm','','0'),
('', 'MPC Water Filter','','0'),
('', 'Grohe Shower Mixer Wall Lever','','0'),
('', 'Kistenmacher Sink Mixer Wall','','0'),
('', 'Lai Tuo Solar Lantern ','','0'),
('', 'Aramix Sink Mixer Wall','','0'),
('', 'Bossini Handle Valve 1.5in','','0'),
('', 'Brezza Handle Valve 0.5in','','0'),
('', 'Formec Handle Valve 2in','','0'),
('', 'Royal Ball Valve 0.75in Brass','','0'),
('', 'Genera Handle Valve 0.5in','','0'),
('', 'Royal Handle Valve 0.5in','','0'),
('', 'PM Bibcock Brass','','0'),
('', 'Turbo Isolator','','0'),
('', 'Super Omega Sink Cock Single','','0'),
('', 'Genera Handle Valve 0.75in','','0'),
('', 'Genera Handle Valve 0.5in','','0'),
('', 'Sanwa Handle Valve 1in','','0'),
('', 'Bossini Handle Valve 0.75in','','0'),
('', 'Bossini Handle Valve 2in','','0'),
('', 'Bossini Handle Valve 1.25in','','0'),
('', 'Aquasan CP Bottle Trap 1.25in','','0'),
('', 'Line Color Screw Driver 2x150mm','','0'),
('', 'Heeco Mirror Clip','','0'),
('', 'Pegler Handle Valve 0.5in Full Bore BP500','','0'),
('', 'Pegler Bibcock Brass 0.5in','','0'),
('', 'Pegler Gate Valve Full Brass 2in ','','0'),
('', 'Jubliee Clip 2in ','','0'),
('', 'Jubilee Clip 3in','','0'),
('', 'Rambo Gate Valve 0.5in Brass','','0'),
('', 'Screw Driver 6x150mm','','0'),
('', 'Oilione Double Tap','','0'),
('', 'ANA Handle Valve 3/4','','0'),
('', 'Pegler  Check Valve 1x0.5in Swing Type','','0'),
('', 'Dorma Door Closer','','0'),
('', 'Pegler Gate Valve Brace Full 1x0.5in','','0'),
('', 'cencled','','0'),
('', 'Jomix Handle Vaalve 3/4','','0'),
('', 'Pegler Handle Valve 0.5in Full Bore PB100','','0'),
('', 'Euro Bibcock 1in','','0'),
('', 'Pegler Gate Valve Full Bore Brass 0.75','','0'),
('', 'Pegler Gate valve Full Bore Brass 0.5in  ','','0'),
('', 'Pegler Gate Valve 0.5in Full Bore','','0'),
('', 'Blanco Selon Mixer Mixer','','0'),
('', 'Doulton Water filter Candle Ceramic','','0'),
('', 'Doulton Water Filter Candle Ceramic (OBE)','','0'),
('', 'Formac Handle Valve 0.5in','','0'),
('', 'Bmeter Water Meter 110mm','','0'),
('', 'Pegler Brass Foot Valve 2in','','0'),
('', 'Pegler Brass Foot Valve 1in','','0'),
('', 'Tangit Glue PVC','','0'),
('', 'Bossini Bibcock 0.5in','','0'),
('', 'Pegler Gate Valve Full Brass 1in','','0'),
('', 'M-Seal','','0'),
('', 'Shellac Gasket','','0'),
('', 'Jomix Gate Valve 0.5in Full Bore','','0'),
('', 'PVC Glue 125g','','0'),
('', 'PVC Glue 250g','','0'),
('', 'PVC Glue 500g','','0'),
('', 'Royal Handle Valve 0.5in','','0'),
('', 'GMSA Silicon Clear','','0'),
('', 'GMSA Silicon White','','0'),
('', 'Super Omega kanseed valve','','0'),
('', 'General Handle Valve 1.25in','','0'),
('', 'Tosum Energy Meter 10(40)','','0'),
('', 'GFC Fan Dimmer','','0'),
('', 'Spot Light Holder','','0'),
('', 'Fischer 10mms','','0'),
('', 'Cable Number 6mm (B)','','0'),
('', 'Cable Number 2.5mm (y)','','0'),
('', 'Cable Number 2.5mm (2)','','0'),
('', 'Cable Number 2.5mm (N)','','0'),
('', 'Cable Number 4mm (7)','','0'),
('', 'Cable Number 6mm (3)','','0'),
('', 'Handel Washer PVC 8mm','','0'),
('', 'Cable Clips 3.5mm','','0'),
('', 'Fischer 5mm','','0'),
('', 'KYK Bearing 6201','','0'),
('', 'IJK Bearing 6000','','0'),
('', 'DPI Bearing 6300','','0'),
('', 'Bulb Reflector 40W R 50 E14','','0'),
('', 'NTN Bearing 6300','','0'),
('', 'LWD Wire clip Round 6.0','','0'),
('', 'Radak Bearing 6202','','0'),
('', 'Connectors 4mm','','0'),
('', 'KBC Bearing 6203','','0'),
('', 'NIS Bearing 6305','','0'),
('', 'Nachi Bearing 6206','','0'),
('', 'KOYO Bearing 6301','','0'),
('', 'KOYO Bearing 6002','','0'),
('', 'KOYO Bearing 6302','','0'),
('', 'KOYO Bearing 6303','','0'),
('', 'KOYO Bearing 6304','','0'),
('', 'Nachi Bearing 6005','','0'),
('', 'Nachi Bearing 6303','','0'),
('', 'Nachi Bearing 6304','','0'),
('', 'MCP Water Filter Candle','','0'),
('', 'Pure water Filter Candle','','0'),
('', 'PM Pressure Control v','','0'),
('', 'Xtra Automatic Control H','','0'),
('', 'Panyi Spare Blade ','','0'),
('', 'Walton Tile cutter Carbibe Tipped','','0'),
('', 'Sun City Hand Blind Riveter','','0'),
('', 'Giken Tile Cutter ','','0'),
('', 'Sanli PP-R Cutter','','0'),
('', 'ROYs Nose Plus','','0'),
('', 'Stanly Nose Plus','','0'),
('', 'Deca Super Cable Cutter','','0'),
('', 'Soap Dispenser Single','','0'),
('', 'Soap Dispenser Double','','0'),
('', 'ModoMix Soap Holder','','0'),
('', 'Nachi Bearing 6302','','0'),
('', 'Nachi Bearing 6301','','0'),
('', 'Nachi Bearing 6304','','0'),
('', 'Nachi Bearing 6305','','0'),
('', 'Nachi Bearing 6300','','0'),
('', 'Nachi Bearing 6000','','0'),
('', 'Nachi Bearing 6200','','0'),
('', 'Nachi Bearing 6002','','0'),
('', 'Nachi Bearing 6003','','0'),
('', 'NSK Bearing 6001','','0'),
('', 'NSK Bearing 6003','','0'),
('', 'NSK Bearing 6201','','0'),
('', 'NSK Bearing 6302','','0'),
('', 'NSK Bearing 6202','','0'),
('', 'NSK Bearing 6203','','0'),
('', 'NSK Bearing 6204','','0'),
('', 'NSK Bearing 6303','','0'),
('', 'NSK Bearing 6205','','0'),
('', 'NSK Bearing 6004','','0'),
('', 'KG Bearing 6205','','0'),
('', 'NSK Bearing 6305','','0'),
('', 'NSK Bearing 6208','','0'),
('', 'waire Proof (E10-1210)','','0'),
('', 'Clipsal DP Switch Two Gang with Neao','','0'),
('', 'Clipsal Flush Switch Two Gang One Way','','0'),
('', 'Clipsal Switch Socket Outlet 15MP','','0'),
('', 'Clipsal Flush Switch Single Gang One way','','0'),
('', 'Clipsal Switch Socket Outlet Twin 13mp','','0'),
('', 'Clipsal Connection  Socket  single','','0'),
('', 'Square-D Pressure Switch','','0'),
('', 'Elettro Pronto Pressure Switch EP-02','','0'),
('', 'Elettro Pronto Pressure Switch  ItalyS','','0'),
('', 'Novex Socket  1 Way 1 Gang W/P 13MP','','0'),
('', 'Novex Switch 2Gang 2Way','','0'),
('', 'Novex Bell Switch 1Gang Waterproof','','0'),
('', 'Hager Breaker 10MP','','0'),
('', 'Hager Breaker 32MP','','0'),
('', 'Hager Breaker 20MP','','0'),
('', 'Magnetic Motor Starter','','0'),
('', 'Novex Socket SW Trailing 2 Gang 13MP','','0'),
('', 'Novex Switch 1Gang 1Way','','0'),
('', 'Novex Switch 2Gang 1Way 3x3','','0'),
('', 'Novex Switch 4Gang 1Way','','0'),
('', 'Novex Switch 3Gang 1Way','','0'),
('', 'Novex Switch 3Gang  W/P 10 Amp ','','0'),
('', 'Novex S/S 13AMP Dubble','','0'),
('', 'Novex S/S 13 Amp ','','0'),
('', 'Novex Lamp Holder (B 22) ','','0'),
('', 'Novex S/S 15AMP  ','','0'),
('', 'Osaka PVC Tape','','0'),
('', 'Gamsa PVC Tape','','0'),
('', 'Novex Switch 6 Gang 3x6','','0'),
('', 'Novex A type 2 gang Rj408 position 8 wire','','0'),
('', 'Aramaix Wash Basin Mixer 2 Hole','','0'),
('', 'Hesanit Wash Basin Mixer Single Lever','','0'),
('', 'Novex Mix Switches','','0'),
('', 'Novex TV Socket 1Gang','','0'),
('', 'Circuler Box Cover Round','','0'),
('', 'Motor Starter China 15/DZ','','0'),
('', 'Novex Tel Socket 1Gang','','0'),
('', 'Novex Blank Plate 1Gang 3x3','','0'),
('', 'Novex Switch 10AMP 3Gang 1Way','','0'),
('', 'Novex Switch Box Cover 3/3','','0'),
('', 'Novex Bell Push','','0'),
('', 'Novex Switch 20AMP 1Gang Double Pole','','0'),
('', 'Novex Telephone Socket 2Gang Scendry','','0'),
('', 'Novex Switch 20AMP 1Gang Double Pole','','0'),
('', 'Klostar Round Wiring Clip (18)','','0'),
('', 'Klostar Wire Clip Round (14)','','0'),
('', 'Klostar Wire Clip Round (10)','','0'),
('', 'Klostar Wire Clip Round (12)','','0'),
('', 'Klostar Wire Clip Round (8)','','0'),
('', 'Klostar Wire Clip Round (7)','','0'),
('', 'Klostar Wire Clip Round (6)','','0'),
('', 'Klostar Wire Clip Round (5)','','0'),
('', 'Klostar Wire Clip Round (4)','','0'),
('', 'Klostar Wire Clip Round (20)','','0'),
('', 'LWD Wire Clip (4.0)','','0'),
('', 'Klostar Wiring Clip Round (9)','','0'),
('', 'Klostar Wiring Clip Round S (12)','','0'),
('', 'Novex GI Box 3/3','','0'),
('', 'NovexGI Box 3/6','','0'),
('', 'Klostar PVC Box 3/3','','0'),
('', 'Multi Plug 2 Pin ','','0'),
('', 'D&B 15AMP Multy Plug','','0'),
('', 'China Plug 13 Amp   ','','0'),
('', 'Kistenmacher W/P Isolater 20 Amp SP','','0'),
('', 'Novex 13Amp  Plug','','0'),
('', 'Zilco 13 Amp Multy  Plug','','0'),
('', 'Brillint Iron Plug','','0'),
('', 'Bolton Iron Plug With Switch','','0'),
('', 'Novex Adapter 13AMP 3Way','','0'),
('', 'Royal Tester Small','','0'),
('', 'Royal Tester Large','','0'),
('', 'Digiton Bell Remote Control','','0'),
('', 'Novex Starter S 10 ','','0'),
('', 'Novex Energy Saver 30W','','0'),
('', 'Novex Mercury Lamp 160W','','0'),
('', 'Novex Mercury Lamp 250W','','0'),
('', 'Novex Mercury Lamp 500W','','0'),
('', 'Rado Door bell','','0'),
('', 'Cooker Socket 45AMP 3Gang','','0'),
('', 'Khaleegia Door Bell','','0'),
('', 'Excel Electronic Door Bell','','0'),
('', 'Novex Door bell','','0'),
('', 'Silver Door Bell Variable','','0'),
('', 'Silver Door Bell Single','','0'),
('', 'Omex Door Bell 4411','','0'),
('', 'Omex Door Bell 4412','','0'),
('', 'Omex Door Bell 4413','','0'),
('', 'Unknown Door Bell ','','0'),
('', 'Novex Met/H Daylight 400W E40','','0'),
('', 'Can','','0'),
('', 'Omex Met/H Daylight 400W','','0'),
('', 'Emergency Light ','','0'),
('', 'Novex D/L 11W E27 3U','','0'),
('', 'Novex D/L 13W 2Pin','','0'),
('', 'Dichro Tester small ','','0'),
('', 'Novex Bulb 100W E27 Frosted','','0'),
('', 'Novex Bulb 60W E27 Frosted','','0'),
('', 'Novex Bulb 60W B22 Clear','','0'),
('', 'Novex Lamp 100W B22 Clear','','0'),
('', 'Novex Energy Saver 13W','','0'),
('', 'FullWat Energy Saver 13W 2u 2pin','','0'),
('', 'Dura Energy Saver 26W','','0'),
('', 'Snowlite S/S 13AMP 2Gang','','0'),
('', 'Snowlite S/S Round-Pin 15Amp','','0'),
('', 'Snowlite S/S 13AMP 1 Gang','','0'),
('', 'C/P Elbow 0.5in','','0'),
('', 'Novex Energy Saver 16W Daylight','','0'),
('', 'Myga Energy Saver 11W','','0'),
('', 'Bossini Handle Valve 2.5in','','0'),
('', 'Osram Sodium Lamp 70W','','0'),
('', 'Librite Energy Saver 9W','','0'),
('', 'Excel Energy Saver 23W Mini E27','','0'),
('', 'Novex Energy Saver 18W','','0'),
('', 'Toxly UV Lamp','','0'),
('', 'Novex Candle Lamp 40W E27','','0'),
('', 'Philips Candle Lamp 40W E14','','0'),
('', 'Novex Energy Saver 11W','','0'),
('', 'Dupro Refrigerator Lamp 15W','','0'),
('', 'Novex Daylight  Spirel 26W E27','','0'),
('', 'Novex Daylight  3U 20W E27','','0'),
('', 'Novex Daylight 2U 9W E14','','0'),
('', 'Novex Fluorescent 2U 26W 2pin','','0'),
('', 'Novex Energy Saver 30W Daylight E27','','0'),
('', 'Eurolite D/L18 W 3U','','0'),
('', 'Novex E/S D/L 15W E27 3U','','0'),
('', 'Cometstar Lamp 5W E27','','0'),
('', 'Novex Lamp 5W E27','','0'),
('', 'Novex Candel Lamp 60W E14','','0'),
('', 'Novex Candel Lamp 40W E 27','','0'),
('', 'Solelux Halogen Lamp 1500W','','0'),
('', 'Solelux Halogen Lamp 1000W','','0'),
('', 'Solelux Halogen Lamp 500W','','0'),
('', 'Dura E/S  18W 4U E 27','','0'),
('', 'Snowlite Energy Saver 26W E27','','0'),
('', 'Novex Halogen Lamp 500W','','0'),
('', 'Novex Elect Choke 50W 12V','','0'),
('', 'APCO Pressure Control Kit Vertical','','0'),
('', 'Novex D/L Round  32W  ','','0'),
('', 'PPR Machine Box 1-2in','','0'),
('', 'Atlas W/F Mob','','0'),
('', 'China Wash Basin Mixer Lever Crystal','','0'),
('', 'Atlas Water Filter Double','','0'),
('', 'Snowlite Ventilation Fan 6in Round','','0'),
('', 'Younas Ventilation Fan 8in Round','','0'),
('', 'Khaleegia Ventilation Fan 9in AutoShutter','','0'),
('', 'Shams Ventilation Fan 8 in Round','','0'),
('', 'Elettro Pronto Float Switch ','','0'),
('', 'Pak Ventilation Fan 8in Round','','0'),
('', 'Pak Ven/Fan Round 8 in                            ','','0'),
('', 'Templair Ventilation Fan Round 6in','','0'),
('', 'Kenwel Ventilation Fan Square6in','','0'),
('', 'Atlas Water Filter Single ','','0'),
('', 'So-Safe Water Filter Single','','0'),
('', 'Astron Ventilation Fan 6in Round','','0'),
('', 'Younas Ventilation Fan 6in Round','','0'),
('', 'Myga Ventilation Fan 6in Round','','0'),
('', 'Avon Exhaust Fan 6in Round','','0'),
('', 'cencled','','0'),
('', 'Fullwat Round Bulb ','','0'),
('', 'Khaleegia Ventilation Fan Plastic Round 6in(K-C6)','','0'),
('', 'Khaleegia Ventilation Fan K-M6','','0'),
('', 'Pak Exhaust Fan Metal with Grill Square 8in','','0'),
('', 'Kenwel Ventilation Fan Plastic Square grill K-K6','','0'),
('', 'Pak ventilation Fan Plastic Round 8in','','0'),
('', 'Tracon Exhaust Fan Auto Shutter 6in','','0'),
('', 'Spirex Ventilation Fan 8in Round NR-20','','0'),
('', 'Novex Water Heater Outlet','','0'),
('', 'Saynora Ventilation Fan 6in Round','','0'),
('', 'Hayashi Ventilation Fan KM-AD8','','0'),
('', 'Hayashi Ventilation Fan (17Hcv)','','0'),
('', 'Kenwel Duct Fan (kn-K6)','','0'),
('', 'CP Jali (Blue)  6X6','','0'),
('', 'Spray Paint White','','0'),
('', 'Spray Paint Grey','','0'),
('', 'Spray Paint Black','','0'),
('', 'Espa Submersible Pump 1HP 8x0.5in Deepwell ','','0'),
('', 'General Fitting Handle Valve 3in','','0'),
('', 'General Fitting Handle Valve 4in','','0'),
('', 'GSESCO Jali 8x8in PVC 3P','','0'),
('', 'Local Jali 6x6in PVC 3P','','0'),
('', 'Jali 6x6in CP xP','','0'),
('', 'Jali 3x3in PVC xP','','0'),
('', 'Jali XxXin PVC xP','','0'),
('', 'Aqua Floor drain with cover ','','0'),
('', 'Paper Holder Box','','0'),
('', 'GSESCO Jali 6x6in PVC 3P','','0'),
('', 'Local Jali 4x4in PVC ','','0'),
('', 'Local Jali 3x3in PVC ','','0'),
('', 'Euro Foot Valve 4in Brass','','0'),
('', 'Pegler Foot Valve 3in Brass','','0'),
('', 'Cancel','','0'),
('', 'Euro Foot Valve 2.5in','','0'),
('', 'XX NR Valve 3in Brass','','0'),
('', 'XX NR Valve 2.5in Brass','','0'),
('', 'XX Check Valve 4in','','0'),
('', 'XX Check Valve 3in','','0'),
('', 'XX Foot Valve 3in Brass','','0'),
('', 'PlasPlugs Wallpaper Stripper','','0'),
('', 'Wash Basin Mixer Clinical','','0'),
('', 'General Fitting Handle Valve 2in','','0'),
('', 'General Fitting Handle Valve 1.5in','','0'),
('', 'Markers Water Pump 0.5HP','','0'),
('', 'Sanwa Bibcock 0.5in Handle Hose','','0'),
('', 'Novex Daylight 16W E27','','0'),
('', 'MJM Pump','','0'),
('', 'Aqua Acid Su 5KG','','0'),
('', 'Valeri Water Pump 1HP','','0'),
('', 'Prakash Water Pump 0.5HP','','0'),
('', 'Kistenmacher Water Pump 0.5HP','','0'),
('', 'Pak Louver Fan 16in','','0'),
('', 'Rustaq Wall Fan 16in','','0'),
('', 'Danway Router / Trimmer','','0'),
('', 'Astron Water Pump 1HP','','0'),
('', 'Younas Wall Fan 16in','','0'),
('', 'Al-Ahmed Wall Fan 18in','','0'),
('', 'Younas Wall Fan 18in','','0'),
('', 'Insect Killer','','0'),
('', 'Buraq Exhaust Fan 12in Metal','','0'),
('', 'Pak Donkey Pump 1HP','','0'),
('', 'Calpeda Swimming Pool Water Pump 1HP','','0'),
('', 'Heeco float control','','0'),
('', 'Buraq Wall Fan 16in','','0'),
('', 'XXX','','0'),
('', 'Tracon Ceiling Fan Duct Type 8in','','0'),
('', 'Solar Fan China','','0'),
('', 'China Motor 4HP 1400RPM 3PH','','0'),
('', 'Calpeda Water Pump 2.5HP','','0'),
('', 'Al-Ahmed Pedestal Fan 18in','','0'),
('', 'GFC Pedestal Fan 24in 2-Blade','','0'),
('', 'Khaleegia Pedestal Fan 30in 3-Blade','','0'),
('', 'GFC Pedestal Fan 24in 4-Blade','','0'),
('', 'GFC Table Fan Medium','','0'),
('', 'Pak Table Fan 16in','','0'),
('', 'Calpeda 7.5HP Centrifugal NM65-12CC','','0'),
('', 'Calpeda 7.5HP Centrifugal NM40-20BE','','0'),
('', 'AquaStar Water Pump 2HP 2X2','','0'),
('', 'Calpeda Water Pump Vertical (Only Pump )','','0'),
('', 'Calpeda Water Motor Vertical 7.5HP (Only Pump)','','0'),
('', 'CNP Vertical Water Pump 3KW CDLF 8-8','','0'),
('', 'Daly Water Pump CDLF 8-140','','0'),
('', 'CNP CDLF 16-5','','0'),
('', 'Prakash Submersible Water Pump 1.5HP','','0'),
('', 'Prakash Submersible Water Pump 2HP','','0'),
('', 'Prakash Submersible Water Pump 1HP','','0'),
('', 'CRI Submersible 1.5HP Comp','','0'),
('', 'CRI Submersible 1HP Uncomp','','0'),
('', 'CRI Submersible 1.5HP Uncomp','','0'),
('', 'Tile Cutter','','0'),
('', 'CRI Drain Pump 0.5KW','','0'),
('', 'Pedllo Water Pump 1HP','','0'),
('', 'Sara Submersible Water Pump 1HP','','0'),
('', 'Xtra Drain Pump 1HP','','0'),
('', 'Daly CDLF Water Pump 16-80','','0'),
('', 'Khaleegia Ventilating Fan 4in K-N4','','0'),
('', 'Khaleegia Ventilating Fan 9in K-M9','','0'),
('', 'CNP CDLF 16-12','','0'),
('', 'Ariston Water Heater Vertical 50L ','','0'),
('', 'Ferrali Water Heater Vertical 50L ','','0'),
('', 'Door Sheet','','0'),
('', 'Paltex Kit','','0'),
('', 'GMSA Contact Adhesive Glue ','','0'),
('', 'Bul Bond','','0'),
('', 'Comap Gas Regulator HP','','0'),
('', 'KED Brooke Round Ventilating Fan 6in','','0'),
('', 'Faisal Ceiling Fan ','','0'),
('', 'Myga Jazz Ceiling Fan','','0'),
('', 'Pak Ventilating Fan P-4','','0'),
('', 'Makita Drill Machine HR2440','','0'),
('', 'GFC Ceiling Fan 56in','','0'),
('', 'PM Sattaf','','0'),
('', 'Zilco Magnetic Switch','','0'),
('', 'Starter Box','','0'),
('', 'Hayashi Ceiling Fan 48in','','0'),
('', 'Nuoua Shattaf','','0'),
('', 'Kistanmacher Shattaf Germany','','0'),
('', 'Unique Shower Head 4-Function','','0'),
('', 'Jomix Short Box','','0'),
('', 'LogicPress Pressure Kit Set M PFLP-20301','','0'),
('', 'Gulf Ceiling Fan 56in','','0'),
('', 'Khaleegia Ceiling Fan 56in','','0'),
('', 'GFC Galaxy Fan','','0'),
('', 'Lucus Drill Machine Large','','0'),
('', 'Lucus Drill Machine Small','','0'),
('', 'Lupas Drill Machine 10mm','','0'),
('', 'Lupus Drill Machine 13mm','','0'),
('', 'Hongdao Angle Grinder 180m','','0'),
('', 'Spray Gun','','0'),
('', 'Novex Fluorescent Lamp 32W Cricular','','0'),
('', 'Mika Fluorescent Lamp 22W Circular','','0'),
('', 'Aqua Plumber Drain Cleaning Tool','','0'),
('', 'Nakai Ventilating Fan Window/Glass','','0'),
('', 'Zilco Circuit Breaker Earth Leakage 4P','','0'),
('', 'Novex Switch Socket Boiler W/P','','0'),
('', 'Hager ELCB 40x300 HP','','0'),
('', 'LS ELCB 63A 4P','','0'),
('', 'Brush 2.5 64mm','','0'),
('', 'AquaStar Water Pump 0.5HP Medium Body','','0'),
('', 'AquasStar Water Pump 0.5HP Small body','','0'),
('', 'CRI Water Pump 0.5HP Small','','0'),
('', 'Harday Water Pump 1HP','','0'),
('', 'cancled','','0'),
('', 'Kirloskar Water Pump 1HP','','0'),
('', 'Korex Water Pump 1HP 1X1','','0'),
('', 'Espa Water Pump 1HP','','0'),
('', 'Fisher Water Pump 1HP','','0'),
('', 'Spray WD-40','','0'),
('', 'Speroni Water Pump 1HP','','0'),
('', 'Nocchi Water Pump 1HP','','0'),
('', 'Calpeda Drain Pump 0.75HP GM10','','0'),
('', 'Nocchi Oil Pump 1HP','','0'),
('', 'SM 3 Phase Induction Motor 2HP','','0'),
('', 'MG2 3 Phase Induction Motor 3HP','','0'),
('', 'MG2 3 Phase Induction Motor 2HP','','0'),
('', 'AGE 3 Phase Induction Motor 1.5HP','','0'),
('', 'Pak Wall Fan 18in','','0'),
('', 'Daly Water Pump 2HP','','0'),
('', 'Daly Water Pump 1HP','','0'),
('', 'Speroni Water Pump 1HP','','0'),
('', 'Pantex Water Pump 1HP','','0'),
('', 'Comet Star Candle Lamp 40W','','0'),
('', 'Carbon Candle','','0'),
('', 'PVC House Pipe','','0'),
('', 'CP Jali 2in','','0'),
('', 'Britmax Tube Fitting  2x20','','0'),
('', 'Megalite mirror light  1x20','','0'),
('', 'Shamas Tube Fitting 1x20','','0'),
('', 'Sicher Tube Fitting 1x20','','0'),
('', 'KED Brooke Tube Fitting 120','','0'),
('', 'Britania Tube Fitting 1x20','','0'),
('', 'Novex Tube Fitting 120','','0'),
('', 'Philips Tube Fitting 1x20','','0'),
('', 'Unknown Tube Fitting 1x20','','0'),
('', 'Pierlite Tube Fitting 1x20','','0'),
('', 'CP Jali 2in','','0'),
('', 'Belt A-29','','0'),
('', 'Belt A-60','','0'),
('', 'Belt A-51','','0'),
('', 'Belt A-55','','0'),
('', 'Belt A-35','','0'),
('', 'Belt A-39','','0'),
('', 'Belt A-34','','0'),
('', 'Belt A-25','','0'),
('', 'Belt A-24','','0'),
('', 'Belt A-27','','0'),
('', 'Belt A-39','','0'),
('', 'Belt A-40','','0'),
('', 'Belt A-37','','0'),
('', 'Belt A-41','','0'),
('', 'Belt Z-39','','0'),
('', 'Belt A-43','','0'),
('', 'Belt A-32','','0'),
('', 'Belt Z-28','','0'),
('', 'Belt Z-27','','0'),
('', 'Belt Z-33','','0'),
('', 'Belt B-50','','0'),
('', 'Belt B-41','','0'),
('', 'Belt B-33','','0'),
('', 'Belt M-34','','0'),
('', 'Belt A-42','','0'),
('', 'Belt M-25','','0'),
('', 'Belt A-45','','0'),
('', 'Belt A-44','','0'),
('', 'Belt A-42','','0'),
('', 'Belt A-46','','0'),
('', 'Belt A-18','','0'),
('', 'Belt A-33','','0'),
('', 'Belt A-28','','0'),
('', 'Belt M-37','','0'),
('', 'Belt M-18','','0'),
('', 'Belt A-20','','0'),
('', 'Belt A-22','','0'),
('', 'Belt M-22','','0'),
('', 'Belt Z-23','','0'),
('', 'Belt B-126/51','','0'),
('', 'Belt A-38','','0'),
('', 'Belt B-88','','0'),
('', 'Belt B-33','','0'),
('', 'Belt Z-36','','0'),
('', 'Belt A-36','','0'),
('', 'Belt B-38','','0'),
('', 'Belt A-30','','0'),
('', 'Belt A-31','','0'),
('', 'Belt M-27','','0'),
('', 'Belt A-43','','0'),
('', 'Belt M-33','','0'),
('', 'Belt Z-37','','0'),
('', 'Belt A-23','','0'),
('', 'Belt M-32','','0'),
('', 'Belt Z-40','','0'),
('', 'Belt Z-54','','0'),
('', 'Belt A-26','','0'),
('', 'Belt M-40','','0'),
('', 'Belt M-38','','0'),
('', 'Belt M-36','','0'),
('', 'Belt Z-29','','0'),
('', 'Belt M-52','','0'),
('', 'Belt Z-38','','0'),
('', 'Belt Z-26','','0'),
('', 'Belt M-26','','0'),
('', 'Belt B-39','','0'),
('', 'Belt A-19','','0'),
('', 'XXX','','0'),
('', 'Belt Fm-31','','0'),
('', 'Belt A22/Z23/A23/A33/A40/A39','','0'),
('', 'Belt Unknown','','0'),
('', 'PM Sink Mixer Double Handle','','0'),
('', 'Crompton Tube Rod 4FT','','0'),
('', 'Philips Tube Rod 4FT','','0'),
('', 'Philips Tube Fitting 4FT','','0'),
('', 'Door Max Tube Fitting 4FT 240','','0'),
('', 'Novex Tube Fitting 4FT 240','','0'),
('', 'Royal Tube Fitting Water Proof','','0'),
('', 'Novex Tube Fitting 4FT 140','','0'),
('', 'Ashford Tube Fitting Single 136W','','0'),
('', 'Telex Fitting Water Proof (F7136WP)','','0'),
('', 'Tuve Fitting 2FT 240V 50Hz','','0'),
('', 'DB Box PVC','','0'),
('', 'Novex Tube Fitting 2FT 120','','0'),
('', 'Emkay Tube Rod Yellow','','0'),
('', 'Britcom Tube Fitting  1x18','','0'),
('', 'Novex Ceiling Rose','','0'),
('', 'Pierlite Channel Tube Fitting 1x18','','0'),
('', 'Mika Fluorescent Lamp 4FT','','0'),
('', 'Britania Fluorescent Tube 4FT','','0'),
('', 'Emkay Tube Rod 2FT Green','','0'),
('', 'Novex Fluorescent Tube 2FT 18W','','0'),
('', 'Compton Fluorescent Tube 2FT 18W','','0'),
('', 'Philips Fluorescent Tube 2FT 18W','','0'),
('', 'Marshal Fluorescent Tube 2FT 18W','','0'),
('', 'Osram Fluorescent Tube 2FT 18W','','0'),
('', 'MaxLux Fluorescent Lamp 8W F6T5','','0'),
('', 'MaxLux Fluorescent Lamp 10W F6T5','','0'),
('', 'Atlas Basin Mixer Single Hole','','0'),
('', 'Jomix Shattaf','','0'),
('', 'Flush Valve xxxx','','0'),
('', 'PM Shower Head Chrome Plated','','0'),
('', 'Gromix Bath Mixer Single Lever','','0'),
('', 'Quromta Bath Mixer Single Lever','','0'),
('', 'Techno Mix Bath Mixer Single Lever','','0'),
('', 'PPR Pipe System Welding Device','','0'),
('', 'Kistenmacher Angle Valve 0.5x0.5in','','0'),
('', 'PM Sink Mixer Single Lever A03','','0'),
('', 'Royal Basin Mixer Single Knob','','0'),
('', 'Royal Bath Mixer 5001-1','','0'),
('', 'PM Wash Basin Double Handle','','0'),
('', 'Windmix Sink Mixer','','0'),
('', 'MAFF Exhaust Fan Round','','0'),
('', 'Deltamix Bidet Mixer','','0'),
('', 'CRI Pump 1HP CTSS-8107M','','0'),
('', 'Parakash Pump 2.0/1.5HP','','0'),
('', 'CRI Pump 1HP CTB-18E/15M','','0'),
('', 'Valeri Pump 1.5HP VP-150','','0'),
('', 'Valeri Pump 1.5HP VP-160/2','','0'),
('', 'Parakash Pump 1.0/0.75 PCP 10','','0'),
('', 'Valeri Pump 0.5HP VP-50','','0'),
('', 'Calpeda Pump NMM 2/A/A','','0'),
('', 'Sicher Basin Mixer','','0'),
('', 'Joflex Shattaf','','0'),
('', 'Bosani Shattaf','','0'),
('', 'GI Tee 4in Thai','','0'),
('', 'GI Tee 4in China','','0'),
('', 'GI Flange 4in','','0'),
('', 'GI Elbow 4in China','','0'),
('', 'GI Reducer Socket 4x3in Thai','','0'),
('', 'GI Reducer Socket 4x2in Thai','','0'),
('', 'GI Reducer Bush 4x3in Thai','','0'),
('', 'GI Reducer Bush 4x1.5in','','0'),
('', 'GI Flange 3in','','0'),
('', 'GI Flange 2in','','0'),
('', 'GI Flange 2.5in','','0'),
('', 'GI Flange 1.25in','','0'),
('', 'GI Flange 1in','','0'),
('', 'GI Flange 1.5in','','0'),
('', 'GI Flange 0.5in','','0'),
('', 'GI Flange 0.75in','','0'),
('', 'XX Flange 1.5in High Pressure','','0'),
('', 'GI Socket 4in','','0'),
('', 'GI Nipple 4in','','0'),
('', 'GI Elbow 4in Thai','','0'),
('', 'GI Union 4in Thai','','0'),
('', 'GI Plagk 4in Thai','','0'),
('', 'GI Elbow 3in China','','0'),
('', 'GI Elbow 3in Thai','','0'),
('', 'GI Elbow 45 3in Thai','','0'),
('', 'GI Union 3in Thai','','0'),
('', 'GI Nipple 3in China','','0'),
('', 'GI Nipple 3in Thai','','0'),
('', 'GI Plagk 3in China','','0'),
('', 'GI Reducer Bush 3x2.5in Thai','','0'),
('', 'GI Reducer Bush 3x1.5in Thai','','0'),
('', 'GI Reducer Bush 3x2in Thai','','0'),
('', 'GI Tee 3in Thai','','0'),
('', 'GI Reducer Bush 3x0.75in Thai','','0'),
('', 'GI Reducer Bush 4x2in China','','0'),
('', 'GI Elbow 2.5in Thai','','0'),
('', 'GI Elbow 2.5in China','','0'),
('', 'GI Nipple Elbow 2.5in Thai','','0'),
('', 'GI Tee 2.5in Thai','','0'),
('', 'GI Nipple 2.5in Thai','','0'),
('', 'GI 4 Way Tee 2in Thai','','0'),
('', 'GI Reducer Tee 2x1.5in Thai','','0'),
('', 'GI Reducer Socket 2x1in Thai','','0'),
('', 'GI Reducer Elbow 2x1in Thai','','0'),
('', 'GI Reducer Bush 2.5x1.25 Thai','','0'),
('', 'GI Union 1.5in Thai','','0'),
('', 'GI Union 1.25in Thai','','0'),
('', 'GI Union 1.25in MS','','0'),
('', 'GI Reducer Tee 1.5x0.75in Thai','','0'),
('', 'GI Reducer Tee 1.5x1in Thai','','0'),
('', 'GI Reducer Tee 1.5x1.25in China','','0'),
('', 'GI Union 0.75in Thai','','0'),
('', 'GI Union 0.5in Thai','','0'),
('', 'GI Reducer Socket 2x0.5in China','','0'),
('', 'GI Reducer Socket 2x0.75in China','','0'),
('', 'GI Reducer Socket 2x1.25in China','','0'),
('', 'GI Reducer Bush 1.25x0.75in China','','0'),
('', 'GI Reducer Bush 1.25x0.5in China','','0'),
('', 'GI Reducer Socket 1.5x1in Thai','','0'),
('', 'GI Reducer Socket 1.5x1in Thai','','0'),
('', 'GI Reducer Elbow 1x0.75in Thai','','0'),
('', 'GI Reducer Elbow 1x0.5in Thai','','0'),
('', 'GI Reducer Elbow 2x1in Thai','','0'),
('', 'GI Reducer Elbow 1.5x1in Thai','','0'),
('', 'GI Reducer Bush 2x0.75in Thai','','0'),
('', 'GI Reducer Bush 2x0.5in Thai','','0'),
('', 'GI Cross Bend 0.5in Thai','','0'),
('', 'GI Rubber Union 1in Thai','','0'),
('', 'Aluminum Tape 2in','','0'),
('', 'GI Socket 1.5in','','0'),
('', 'GI Bush 2.5x2in','','0'),
('', 'GI Bush 2.5x1.5in','','0'),
('', 'GI Bush 2x0.5in','','0'),
('', 'GI Bush 2x1in','','0'),
('', 'GI Bush 1.5x1.25in','','0'),
('', 'GI Bush 2x1.5in','','0'),
('', 'XX Flange 2in High Pressure','','0'),
('', 'Omex Sport Light 50W','','0'),
('', 'GI Socket 2.5in Thai','','0'),
('', 'GI Reducer Socket 2x1.5in Thai','','0'),
('', 'Kistanmacher Shattaf Duplicate ','','0'),
('', 'Heeco Shower Flexible Pipe PVC ','','0'),
('', 'Family Ship Shattaf','','0'),
('', 'XXX','','0'),
('', 'Tanghetti Shattaf','','0'),
('', 'Zuhoor Shattaf','','0'),
('', 'Raya Shattaf','','0'),
('', 'Biba Shattaf','','0'),
('', 'Ludher Shattaf','','0'),
('', 'GS Esco Shattaf','','0'),
('', 'PVC Spiral Hose','','0'),
('', 'Modomix Shattaf','','0'),
('', 'GFC Louver Fan 14in','','0'),
('', 'GFC Bracket Fan 18in','','0'),
('', 'GFC Circumatic Fan 18in','','0'),
('', 'Pak Bracket Fan 18in','','0'),
('', 'Belvin Bracket Fan 18in','','0'),
('', 'Buraq Table Fan 16in','','0'),
('', 'Buraq Stand Fan 16in','','0'),
('', 'Buraq Table Fan 16in 6 blade AC/DC','','0'),
('', 'Pak Stand Fan 30in Industrial','','0'),
('', 'Pak Wall Fan 26in Industrial','','0'),
('', 'Pak Stand Fan 24in Industrial','','0'),
('', 'Pak Wall Fan 24in  Industrial','','0'),
('', 'Pak Floor/Desk Fan 18in','','0'),
('', 'Pak Floor/Desk Fan 16in','','0'),
('', 'Pak Louver Box Fan 14in','','0'),
('', 'Pak Louver Bracket Fan','','0'),
('', 'Pak Louver Pedestal Fan','','0'),
('', 'Kenwel Wall Fan 16in Electric','','0'),
('', 'Khaleegia Wall Fan 16in Electric','','0'),
('', 'Pak Ventilation Fan 6in Window','','0'),
('', 'Pak Ventilation Fan 16in Heavy Duty','','0'),
('', 'Pak Propeller Exhaust Fan 12in','','0'),
('', 'Pak Ventilator Fan 12in GH-30','','0'),
('', 'Pak Shutter Exhaust Fan 12in','','0'),
('', 'Pak Shutter Exhaust Fan  8in','','0'),
('', 'Buraq Ventilation Fan 12in Heavy Duty','','0'),
('', 'BHD 30','','0'),
('', 'Buraq Ventilation Fan 12in Industrial','','0'),
('', 'Khaleegia Exhaust Fan xxin Industrial W/S','','0'),
('', 'Khaleegia Ventilation Fan 9in Heavy Duty','','0'),
('', 'Khaleegia Ventilation Fan 12in Industrial KA1230','','0'),
('', 'XXX','','0'),
('', 'Khaleegia Exhaust Fan 16in Industrial W/S','','0'),
('', 'Younas Exhaust Fan 18in','','0'),
('', 'Buraq Ventilation Fan 18in Heavy Duty','','0'),
('', 'Khaleegia Ventilation Fan 6in Industrial KA0615','','0'),
('', 'Khaleegia Ventilation Fan 9in K-M9','','0'),
('', 'Khaleegia Ventilation Fan xxin K-AC10','','0'),
('', 'Khaleegia Ventilation Fan 6in K-N6','','0'),
('', 'Khaleegia Ventilation Fan 6in K-M6','','0'),
('', 'Khaleegia Ventilation Fan 4in K-N4','','0'),
('', 'Pak Ventilation Fan P-4','','0'),
('', 'Younas Ventilation Fan 8in YEG-8','','0'),
('', 'Younas Exhaust Fan 8in Industrial W/C','','0'),
('', 'Younas Exhaust Fan 9in Metal','','0'),
('', 'Khaleegia Duct Pipe Flexible 12x5m KFD-30','','0'),
('', 'Khaleegia Duct Pipe Flexible 10x5m KFD-25','','0'),
('', 'Naff Ventilation Fan xxxx','','0'),
('', 'Super General Ventilation Fan 8in','','0'),
('', 'Myga Ventilation Fan 8in Window','','0'),
('', 'Naff Ventilation Fan xxxx Industrial','','0'),
('', 'Myga Ventilation Fan 6in Window','','0'),
('', 'Spirex Ventilation Fan 10in ','','0'),
('', 'Spirex Ventilation Fan 8in','','0'),
('', 'Doormax Ventilation Fan 8in','','0'),
('', 'Templair Ventilation Fan V-TA-8','','0'),
('', 'Pak Ventilation Fan 8in N-6','','0'),
('', 'Pak Ventilator 10in','','0'),
('', 'Roma Shattaf New','','0'),
('', 'Pak Ceiling Fan Galaxy Gold','','0'),
('', 'Pak Pedestal Fan 24in','','0'),
('', 'Pak Exhaust Fan 8in Light Duty W/G','','0'),
('', 'Kenwel Ventilation Fan KN-AD8','','0'),
('', 'Kenwel Ventilation Fan KN-AD8','','0'),
('', 'Kenwel Ventilation Fan KN-AD6','','0'),
('', 'Kenwel Bathroom Fan 15/6in K-K6','','0'),
('', 'Pak Ventilator 12in Portable','','0'),
('', 'Younas Exhaust Fan 16in','','0'),
('', 'Hose Pipe Roll-Flat 30FT','','0'),
('', 'Voylet Spray Gun','','0'),
('', 'Younas Ventilation Fan 12in','','0'),
('', 'Hayashi Ventilation Fan xxin 24HCV','','0'),
('', 'Hayashi Ventilation Fan xxin 25HCV','','0'),
('', 'Super Miraj Water Heater 50G Horizontal','','0'),
('', 'D-Rain Toilet Seat and Cover','','0'),
('', 'ASI Uni Flo Toilet Seat','','0'),
('', 'WC Seat Toilet Seat Cover White','','0'),
('', 'PTFE Tapes 0.5inx0.075mm  Hees','','0'),
('', 'Novex Batten Fitting 1x40','','0'),
('', 'Novex Batten Fitting 2x40','','0'),
('', 'Novex Batten Fitting 1x20','','0'),
('', 'Novex Batten Fitting 2x20','','0'),
('', 'Novex Batten Fitting 2x20','','0'),
('', 'Philips Batten Fitting 2FT 2x18','','0'),
('', 'Philips Batten Fitting xxFT 1x18','','0'),
('', 'Philips Batten Fitting 4FT 3x36','','0'),
('', 'Philips Batten Fitting 4FT 1x36','','0'),
('', 'Excel Batten Fitting 2FT 1X20 Double','','0'),
('', 'AshFord Fluourescent Grill Fitting 4FT 1x36','','0'),
('', 'Omex Fixture Waterproof 4FT 2x36','','0'),
('', 'Britan_Nia Fluourescent Batten xxx 4FT 1x40','','0'),
('', 'Novex Fixture 4FT 2x40 Waterproof','','0'),
('', 'Atlantis xxx Fitting 4FT Waterproof Dustproof','','0'),
('', 'Pierlite Flourescent Fixture Channel Fitting Economy 18W','','0'),
('', 'Crompton Daylight 4FT 36W','','0'),
('', 'Crompton Daylight 2FT 18W','','0'),
('', 'Emkay Tube Rod 2FT Yellow','','0'),
('', 'Galaxy Daylight Rod 4FT 35W','','0'),
('', 'Ked Brooke Tube Light 1x20  ','','0'),
('', 'Myga Tube Fixture 1x20','','0'),
('', 'Flourescent Mirror Light 1x15','','0'),
('', 'Belano Bath Mixer Single Lever','','0'),
('', 'Usong Down Light 150W White','','0'),
('', 'Usong Down Light 150W','','0'),
('', 'Usong Down Light 150W 2x20','','0'),
('', 'Usong Down Light  70W White','','0'),
('', 'Usong Lamps 60W White Aluminium Die-Casting Bulkhead','','0'),
('', 'Usong Lamps 100W White Aluminium Die-Casting Bulkhead','','0'),
('', 'Usong Lamps 60W White Aluminium Die-Casting Bulkhead B01','','0'),
('', 'Usong Lamps 60W White Aluminium Die-Casting Bulkhead B02','','0'),
('', 'Garden Lamp','','0'),
('', 'GFC Exhaust Fan 8in Metal','','0'),
('', 'Younas Ventilation Fan 6in Delux','','0'),
('', 'Ventilation Grill MV 250/150 US','','0'),
('', 'Novex Surface Mounting Box 3x6in White','','0'),
('', 'Sonic Drain Cover 15x15cm','','0'),
('', 'Submarine Wire 3x2.5mm ','','0'),
('', 'Unkown CP Jali 15x15cm','','0'),
('', 'Aqua Steel  CP Jali 15x15cm','','0'),
('', 'Novex Starter  S 2','','0'),
('', 'So Pure Water Purification System Dual','','0'),
('', 'Klastar PVC Box 3x3','','0'),
('', 'Junex Water Heater xxx 12G 50','','0'),
('', 'Junex Water Heater Horizontal','','0'),
('', 'Barid Hot Water Heater Horizontal','','0'),
('', 'Everhot Water Heater Vertical 50L','','0'),
('', 'National Water Heater Horizontal 12G','','0'),
('', 'GMSA Super Glue','','0'),
('', 'Nova Flush-cisten Machenisum ','','0'),
('', 'Ariston Water Heater Super G R 80 ','','0'),
('', 'Halogen Holder AD73/76-WH','','0'),
('', 'Halogen Holder AD73/76-CHR','','0'),
('', 'Halogen Holder AD73/76-GID','','0'),
('', 'Hitachi Ring Light 20W FC6T9/D','','0'),
('', '110 Multiple Outlet Socket','','0'),
('', 'Novex Bell Switch 1Gang Waterproof','','0'),
('', 'Kistanmacher Bell Switch 1Gang Waterproof','','0'),
('', 'Kistanmacher Socket Outlet with 1Gang Switch Waterproof','','0'),
('', 'Kistanmacher Switch 1Gang Waterproof','','0'),
('', 'AEG Motor 1.5HP 1400RPM 3Phase','','0'),
('', 'AEG Motor 5.5HP 2900RPM 3Phase','','0'),
('', 'China Motor 1400RPM 1Phase','','0'),
('', 'Adjustable Wrench 12in','','0'),
('', 'Pipe Wrench 24in','','0'),
('', 'Pulling Spring 20m','','0'),
('', 'Pulling Spring 25m','','0'),
('', 'Pulling Spring 30m','','0'),
('', 'Naaf Exhaust Fan 8in Round Glass RMA-8','','0'),
('', 'Astrom Ventilation Fan 8in','','0'),
('', 'Novex Halogen Lamp M-NFL9107','','0'),
('', 'Novex Down Light M-KL1623','','0'),
('', 'NEC Fluorescent Lamp Circular','','0'),
('', 'Splendor Mercury Bulb 100W','','0'),
('', 'Splendor Mercury Bulb 150W','','0'),
('', 'Khaleegia Ventilation Fan 8in K-AC8','','0'),
('', 'Venezia Hand Shower Shut-off Italy','','0'),
('', 'pak Circomatic Fan 18in','','0'),
('', 'Pak ceiling Fan Jazz 56in','','0'),
('', 'Pak Ceiling Fan Galaxy Gold 56in','','0'),
('', 'Sonex Ceiling Fan 56in Bravo','','0'),
('', 'Saynora Ceiling Fan 56in','','0'),
('', 'Pak Shutter Fan 16in (F910-40)','','0'),
('', 'Pak Shutter Fan 18in (Fa10-45)','','0'),
('', 'Juble Clip 000','','0'),
('', 'Novex Tube Rod 2ft (18W)','','0'),
('', 'Novex 15 Round Pm Plug (W)','','0'),
('', 'CP Tee 0.5in','','0'),
('', 'CP R/Bush 0.75x0.5in ','','0'),
('', 'CP Socket 0.5in','','0'),
('', 'XXX','','0'),
('', 'CP Reducer Socket 0.75x0.5in','','0'),
('', 'CP Nipple 0.5in','','0'),
('', 'CP Nipple Socket 0.5x0.5in 30mm','','0'),
('', 'CP Nipple Socket 0.5x0.5in 50mm','','0'),
('', 'CP Nipple Socket 0.5x0.5in 40mm','','0'),
('', 'CP Nipple Socket 0.5x0.5in 25mm','','0'),
('', 'CP NIPPLE SOcket 0.5x0.5in 27mm','','0'),
('', 'CP NIPPLE SOCKEt 0.5x0.5in 15mm','','0'),
('', 'CP NIPPLE SOCKEt 0.5x0.5in 10mm','','0'),
('', 'CP NIPPLE SOCKEt 0.5x0.5in 20mm','','0'),
('', 'CP NIPPLE SOCKEt 0.5x0.375','','0'),
('', 'Pegler Gate Valve 1x0.25','','0'),
('', 'Brass 4 Way Tee','','0'),
('', 'GM Side Pller Cock','','0'),
('', 'Han Sanitar Shattaf Germany ','','0'),
('', 'XXX','','0'),
('', 'Espa Water Pump 0.8HP ','','0'),
('', 'GroundFos Water Pump 1HP','','0'),
('', 'CRI Submersible Drainage  Pump 1HP 2in Outlet','','0'),
('', 'Calpeda Water Pump 1Hp (NMM2)','','0'),
('', 'PM Single Lever Sink Mixer Brass Body (A04)','','0'),
('', 'Belano single Lever Basin mixer','','0'),
('', 'CALPEDA  Water PUMP 0.5HP TM61E ','','0'),
('', 'CALPEDA  Water PUMP 0.5HP CTM60 ','','0'),
('', 'CALPEDA  Water PUMP 0.5HP CT61 ','','0'),
('', 'Zenit Water Pump 0.375KW ','','0')
;
